### ISSUE TITLE
Difficult terrain multiplying entire path

### ISSUE THREAD

**Issue by pcwilcox** [ironmonk88/TerrainLayer#3]
(If this should be reported somewhere else let me know)

It seems that this is multiplying the entire path distance instead of only the squares marked as difficult:
![image](https://user-images.githubusercontent.com/14306303/110415129-3b60b300-8089-11eb-9cf1-c46cd21a49c3.png)

This is using drag ruler, difficult terrain, terrain layer.

**Comment by ironmonk88** [comment]
Pretty sure that's an issue with Difficult Terrain.  
It's actually explained with the module that you need to set waypoints when changing between terrain difficulties.
And technically, Terrain Layer shouldn't be doing any of the calculations, that's up to the Ruler to calculate the cost and display the value.
