### ISSUE TITLE
Incompatiability with Furnace Mod

### ISSUE THREAD

**Issue by UnoriginalDM** [ironmonk88/TerrainLayer#5]
I am not sure how this mod is affecting the drawing tools, but once you have this enabled and the furnace mod. You can no longer use the "square" drawing tool. I believe this issue is a carry over from the original. If I find a solution I will let you know.

![image](https://user-images.githubusercontent.com/77896718/110614202-b7c1c780-8157-11eb-88c0-65100a6f5c02.png)
![image](https://user-images.githubusercontent.com/77896718/110614271-c90ad400-8157-11eb-9d34-cc2889ccf993.png)

**Comment by ironmonk88** [comment]
That was really weird.  Thanks to FXMaster for a code example to work off of.  Should be fixed int he next release.

**Comment by ironmonk88** [comment]
1.0.4 has been released.
